package effio

import (
	"log"
	"os"
	"path"
)

func (cmd *Cmd) GraphSuite() {
	var idFlag, pathFlag string
	fs := cmd.FlagSet
	fs.StringVar(&pathFlag, "path", "suites/", "suite path, as generated by effio make")
	fs.StringVar(&idFlag, "id", "", "Id of the test suite")
	fs.Parse(cmd.Args)

	jsonPath := path.Join(pathFlag, idFlag, "suite.json")
	_, err := os.Stat(jsonPath)
	if err != nil {
		log.Fatalf("Could not stat file '%s': %s\n", jsonPath, err)
	}

	s := LoadSuiteJson(jsonPath)
	s.Graph(pathFlag)
}
