package effio

import (
	"log"
	"os"
	"path"
)

// effio run -suite <dir>
func (cmd *Cmd) RunSuite() {
	// parse subcommand arguments
	var idFlag, pathFlag string
	var rerunFlag bool
	fs := cmd.FlagSet
	// TODO: require arguments
	fs.StringVar(&pathFlag, "path", "suites/", "suite path, as generated by effio make")
	fs.StringVar(&idFlag, "id", "", "Id of the test suite")
	fs.BoolVar(&rerunFlag, "rerun", false, "rerun tests even if output.json already exists")
	fs.Parse(cmd.Args)

	jsonPath := path.Join(pathFlag, idFlag, "suite.json")
	_, err := os.Stat(jsonPath)
	if err != nil {
		log.Fatalf("Could not stat file '%s': %s\n", jsonPath, err)
	}

	s := LoadSuiteJson(jsonPath)
	s.Run(pathFlag, rerunFlag)
}
