package effio

import (
	"log"
	"os"
	"path"
)

// effio run -suite <dir>
func (cmd *Cmd) RunSuite() {
	// parse subcommand arguments
	var suiteFlag string
	fs := cmd.FlagSet
	fs.StringVar(&suiteFlag, "suite", "conf/", "suite directory, as generated by effio make")
	fs.Parse(cmd.Args)

	jsonPath := path.Join(suiteFlag, "suite.json")
	_, err := os.Stat(jsonPath)
	if err != nil {
		log.Fatalf("Could not stat file '%s': %s\n", jsonPath, err)
	}

	s := LoadSuiteJson(jsonPath)

	log.Printf("Suite: %v\n", s)
}
